config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :projects
  root "projects#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :projects, :dependent => :delete_all
  accepts_nested_attributes_for :projects, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
 devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( :email, :password, :password_confirmation, :name, :address) }
 end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
   { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
 end

 def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
             concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
             concat message
           end)
   end
   nil
 end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TipiTest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
   <% end %>
   <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
  <% end %>
    <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "TipiTest" %></div>
            <nav class="collapse navbar-collapse navbar-ex1-collapse">
                <% if user_signed_in? -%>
  						        <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to current_user.name %></li>
          							<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                      </ul>
                      <ul class="nav navbar-nav navbar-left">
                        <li><%= link_to 'Project', projects_path %></li>
                        <li><%= link_to 'Users', users_index_path %></li>
                    </ul>
                    <%else%>
                    <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to "Login In", new_user_session_path %></li>
                      <li><%= link_to "Register", new_user_registration_path %></li>
                    </ul>
               <%end%>
          </nav>
        </div>
      </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-body">
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, class:"control-label" %>
    <%= form.text_area :description, id: :project_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %><br>
      <%= form.select(:user_id, User.all.map{|u|[u.name, u.id]} ,class: "form-control" )  %>
  </div>
<center>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
</center>
<% end %>
<div>

app/views/projects/edit.html.erb
<center>
<div class="panel-heading">
<h1>Edit Project</h1>
</div>
</center>
<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<center>
 <h1>All Projects</h1>
</center>
<br><br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.description %></td>
          <td><%= project.user.name%></td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<center>
  <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
<br>
 <%= link_to 'New Project', new_project_path, class:"btn btn-default" %>
</center>

app/views/projects/new.html.erb
<center>
<div class="panel-heading">
<h1>New Project</h1>
</div>
</center>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class:"btn btn-warning" %>

app/views/projects/show.html.erb
<center>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.name  %>
</p>

<%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary" %> |
<%= link_to 'Back', projects_path, class: "btn btn-warning" %>
</center>

app/views/users/index.html.erb
<center>
 <h1>All Users</h1>
</center>
<br><br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.address %></td>
          <td><%= user.email%></td>

        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<center>
<br>
</center>